In [7]:
from pathlib import Path

import numpy as np
import pandas as pd

In [12]:
def parse_line(l):
    s3url = l.split(' ')[-1]
    var, chunk = s3url.split('/')[-2:]
    return var, chunk

def filter_files(chunk):
    if chunk in {'.zattrs', '.zgroup', '.zmetadata', '.zarray'}:
        return False
    return True

def get_df2d(path):
    t = path.read_text()
    ls = [l for l in t.split('\n') if l]
    
    vars_chunks = [([var] + chunk.split('.')) for var, chunk in [parse_line(l) for l in ls] if filter_files(chunk)]
    
    df = pd.DataFrame(((vc[0], int(vc[1]), int(vc[2])) for vc in vars_chunks if len(vc) == 3), columns=['var', 'c1', 'c2'])
    return df

def get_df3d(path):
    t = path.read_text()
    ls = [l for l in t.split('\n') if l]
    
    vars_chunks = [([var] + chunk.split('.')) for var, chunk in [parse_line(l) for l in ls] if filter_files(chunk)]
    
    df = pd.DataFrame(((vc[0], int(vc[1]), int(vc[2]), int(vc[3])) for vc in vars_chunks if len(vc) == 4), columns=['var', 'c1', 'c2', 'c3'])
    return df
   

In [13]:
df2d = get_df2d(Path('/home/users/mmuetz/s3snafu/s3cmd_ls_glm.n2560_RAL3p3.um.PT1H.hp_z10.zarr'))

In [10]:
unique_vars = df2d['var'].unique()

for var in unique_vars:
    c1arr = df2d[df2d['var'] == var].sort_values(by='c1').groupby('c1').count().index.values
    a = np.arange(c1arr[-1] + 1)
    missing = np.ones(c1arr[-1] + 1).astype(bool)
    missing[c1arr] = False
    if len(a[missing]):
        if len(a[missing]) >= 3:
            print(var, a[missing][[0, 1, -1]])
        else:
            print(var, a[missing][0:1])
    else:
        print(var, 'complete')

clivi [5497 5498 7764]
clt [5497 5498 7764]
clwvi [5497 5498 7764]
hflsd [0]
hfssd [0]
huss complete
pr [   0 5497 7764]
prs [   0 5497 7764]
prw [5497 5498 7764]
ps [0]
psl [5497 5498 7764]
rlds complete
rldscs complete
rlut complete
rlutcs complete
rsds complete
rsdscs complete
rsdt [0]
rsut complete
rsutcs complete
tas complete
ts complete
uas complete
vas complete


In [15]:
df3d = get_df3d(Path('/home/users/mmuetz/s3snafu/s3cmd_ls_glm.n2560_RAL3p3.um.PT3H.hp_z10.zarr'))

In [17]:
unique_vars = df3d['var'].unique()

for var in unique_vars:
    c1arr = df3d[df3d['var'] == var].sort_values(by='c1').groupby('c1').count().index.values
    a = np.arange(c1arr[-1] + 1)
    missing = np.ones(c1arr[-1] + 1).astype(bool)
    missing[c1arr] = False
    if len(a[missing]):
        if len(a[missing]) >= 3:
            print(var, a[missing][[0, 1, -1]])
        else:
            print(var, a[missing][0:1])
    else:
        print(var, 'complete')

cli [0]
clw [0]
hur complete
hus complete
qg [0]
qr [0]
qs [0]
ta complete
ua complete
va complete
wa complete
zg complete


In [60]:
c1arr = df[df['var'] == 'clivi'].sort_values(by='c1').groupby('c1').count().index.values

In [93]:
count = df[df['var'] == 'clivi'].sort_values(by='c1').groupby('c1').count()

In [95]:
count[count.c2 != 12]

,var,c2
c1,,


In [61]:
c1arr

array([   0,    1,    2, ..., 9742, 9743, 9744])

In [72]:
a = np.arange(9745)
missing = np.ones(9745).astype(bool)

In [73]:
missing[c1arr] = False

In [74]:
a[missing]

array([5497, 5498, 5499, ..., 7762, 7763, 7764])

In [79]:
a[missing][1:][(np.diff(a[missing]) != 1)]

array([5521, 5545, 5569, 5593, 5617, 5641, 5665, 5689, 5713, 5737, 5761,
       5785, 5809, 5833, 5857, 5881, 5905, 5929, 5953, 5977, 6001, 6025,
       6049, 6073, 6097, 6121, 6145, 6169, 6193, 6217, 6241, 6265, 6289,
       6313, 6337, 6361, 6385, 6409, 6433, 6457, 6481, 6505, 6529, 6553,
       6577, 6601, 6625, 6649, 6673, 6697, 6721, 6745, 6769, 6793, 6817,
       6841, 6865, 6889, 6913, 6937, 6961, 6985, 7009, 7033, 7057, 7081,
       7105, 7129, 7153, 7177, 7201, 7225, 7249, 7273, 7297, 7321, 7345,
       7369, 7393, 7417, 7441, 7465, 7489, 7513, 7537, 7561, 7585, 7609,
       7633, 7657, 7681, 7705, 7729, 7753])

In [98]:
a[missing]

array([0])