In [2]:
import math as maths

import cartopy.crs as ccrs
import intake
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr

import easygems.healpix as egh

/home/users/mmuetz/miniforge3/envs/hackathon_env/lib/python3.12/site-packages/pyproj/network.py:59: UserWarning: pyproj unable to set PROJ database path.
  _set_context_ca_bundle_path(ca_bundle_path)


In [3]:
import warnings

# Suppress specific FutureWarnings matching the message pattern when using cat[...].to_dask()
warnings.filterwarnings(
    "ignore",
    message=".*The return type of `Dataset.dims` will be changed.*",
    category=FutureWarning,
)

In [4]:
cat = intake.open_catalog('https://digital-earths-global-hackathon.github.io/catalog/catalog.yaml')['online']

In [4]:
# Open a dataset.
ds = cat['um_glm_n2560_RAL3p3'](zoom=10, time='PT1H').to_dask()

In [6]:
ds.isel(time=5496).clivi.values

array([2.0719042e-05, 1.0000793e-05, 9.4107418e-06, ..., 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00], dtype=float32)

In [7]:
ds.isel(time=5497).clivi.values

array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)

In [8]:
ds.isel(time=7764).clivi.values

array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)

In [9]:
ds.isel(time=7765).clivi.values

array([0.        , 0.        , 0.        , ..., 0.00508104, 0.00352667,
       0.00351909], dtype=float32)

In [11]:
ds.isel(time=slice(5496, 7765)).time

<xarray.DataArray 'time' (time: 2269)> Size: 18kB
array(['2020-09-05T00:00:00.000000000', '2020-09-05T01:00:00.000000000',
       '2020-09-05T02:00:00.000000000', ..., '2020-12-08T10:00:00.000000000',
       '2020-12-08T11:00:00.000000000', '2020-12-08T12:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
    crs      float64 8B ...
  * time     (time) datetime64[ns] 18kB 2020-09-05 ... 2020-12-08T12:00:00

In [5]:
ds9 = cat['um_glm_n2560_RAL3p3'](zoom=9, time='PT1H').to_dask()

In [7]:
ds9.isel(time=5496).clivi.values

array([1.1172917e-05, 1.9287295e-06, 1.8704560e-06, ..., 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00], dtype=float32)

In [8]:
ds9.isel(time=5497).clivi.values

array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)

In [9]:
ds8 = cat['um_glm_n2560_RAL3p3'](zoom=8, time='PT1H').to_dask()

In [14]:
ds8.isel(time=5497).clivi.values

array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)

In [15]:
cat['um_glm_n2560_RAL3p3'](zoom=7, time='PT1H').to_dask().isel(time=5497).clivi.values

array([nan, nan, nan, ..., nan, nan, nan], dtype=float32)