In [1]:
import sys
sys.path.insert(0, '/home/users/mmuetz/deploy/wcrp_hackathon/scripts/process_um_data')
from pathlib import Path

import pandas as pd

In [2]:
import um_slurm_control as usc

/home/users/mmuetz/miniforge3/envs/hackathon_base_env/lib/python3.12/site-packages/pyproj/network.py:59: UserWarning: pyproj unable to set PROJ database path.
  _set_context_ca_bundle_path(ca_bundle_path)


In [3]:
d2p = usc.find_dyamond3_pp_dates_to_paths(Path('/gws/nopw/j04/kscale/DYAMOND3_data/5km-RAL3/glm'))

2025-07-25 11:04:27.560 | DEBUG    | um_slurm_control:find_dyamond3_pp_dates_to_paths:109 - found 3623 pp paths
2025-07-25 11:04:27.678 | DEBUG    | um_slurm_control:find_dyamond3_pp_dates_to_paths:123 - found 812 complete dates


In [4]:
d2p[pd.Timestamp('2020-01-20')]

[PosixPath('/gws/nopw/j04/kscale/DYAMOND3_data/5km-RAL3/glm/field.pp/apvera.pp/glm.n2560_RAL3p3.apvera_20200120T00.pp'),
 PosixPath('/gws/nopw/j04/kscale/DYAMOND3_data/5km-RAL3/glm/field.pp/apverb.pp/glm.n2560_RAL3p3.apverb_20200120T00.pp'),
 PosixPath('/gws/nopw/j04/kscale/DYAMOND3_data/5km-RAL3/glm/field.pp/apverc.pp/glm.n2560_RAL3p3.apverc_20200120T00.pp'),
 PosixPath('/gws/nopw/j04/kscale/DYAMOND3_data/5km-RAL3/glm/field.pp/apverd.pp/glm.n2560_RAL3p3.apverd_20200120T00.pp')]

In [5]:
import iris

In [6]:
c1 = iris.load(d2p[pd.Timestamp('2020-01-20')][0])

In [ ]:
c2 = iris.load(d2p[pd.Timestamp(d)][i] for d in pd.date_range('2020-01-20 00:00', '2020-01-22 12:00', freq='12h') for i in range(4))

/home/users/mmuetz/miniforge3/envs/hackathon_base_env/lib/python3.12/site-packages/iris/common/mixin.py:203: FutureWarning: You are using legacy date precision for Iris units - max precision is seconds. In future, Iris will use microsecond precision - available since cf-units version 3.3 - which may affect core behaviour. To opt-in to the new behaviour, set `iris.FUTURE.date_microseconds = True`.
  warnings.warn(message, category=FutureWarning)
/home/users/mmuetz/miniforge3/envs/hackathon_base_env/lib/python3.12/site-packages/iris/common/mixin.py:203: FutureWarning: You are using legacy date precision for Iris units - max precision is seconds. In future, Iris will use microsecond precision - available since cf-units version 3.3 - which may affect core behaviour. To opt-in to the new behaviour, set `iris.FUTURE.date_microseconds = True`.
  warnings.warn(message, category=FutureWarning)
/home/users/mmuetz/miniforge3/envs/hackathon_base_env/lib/python3.12/site-packages/iris/common/mixin.p

In [27]:
c2

[<iris 'Cube' of m01s01i202 / (unknown) (forecast_period: 25; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of m01s09i223 / (unknown) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of air_temperature / (K) (forecast_period: 25; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of dew_point_temperature / (K) (forecast_period: 25; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of land_binary_mask / (1) (time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of sea_ice_area_fraction / (1) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of specific_humidity / (1) (forecast_period: 25; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_air_pressure / (Pa) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_altitude / (m) (time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_longwave_flux_in_air / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_longwave_flux_in_air_assuming_clear_sky / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_shortwave_flux_in_air / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_shortwave_flux_in_air_assuming_clear_sky / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_net_downward_longwave_flux / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_temperature / (K) (forecast_period: 25; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_upward_latent_heat_flux / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_upward_sensible_heat_flux / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_upwelling_shortwave_flux_in_air_assuming_clear_sky / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_incoming_shortwave_flux / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_longwave_flux / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_longwave_flux_assuming_clear_sky / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_shortwave_flux / (W m-2) (forecast_period: 25; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_shortwave_flux / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_shortwave_flux_assuming_clear_sky / (W m-2) (forecast_period: 24; forecast_reference_time: 3; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of x_wind / (m s-1) (forecast_period: 25; forecast_reference_time: 3; latitude: 3841; longitude: 5120)>,
<iris 'Cube' of y_wind / (m s-1) (forecast_period: 25; forecast_reference_time: 3; latitude: 3841; longitude: 5120)>]

In [7]:
c1

/home/users/mmuetz/miniforge3/envs/hackathon_base_env/lib/python3.12/site-packages/iris/common/mixin.py:203: FutureWarning: You are using legacy date precision for Iris units - max precision is seconds. In future, Iris will use microsecond precision - available since cf-units version 3.3 - which may affect core behaviour. To opt-in to the new behaviour, set `iris.FUTURE.date_microseconds = True`.
  warnings.warn(message, category=FutureWarning)


[<iris 'Cube' of m01s01i202 / (unknown) (time: 13; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of m01s09i223 / (unknown) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of air_temperature / (K) (time: 13; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of dew_point_temperature / (K) (time: 13; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of land_binary_mask / (1) (latitude: 3840; longitude: 5120)>,
<iris 'Cube' of sea_ice_area_fraction / (1) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of specific_humidity / (1) (time: 13; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_air_pressure / (Pa) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_altitude / (m) (latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_longwave_flux_in_air / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_longwave_flux_in_air_assuming_clear_sky / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_shortwave_flux_in_air / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_downwelling_shortwave_flux_in_air_assuming_clear_sky / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_net_downward_longwave_flux / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_temperature / (K) (time: 13; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_upward_latent_heat_flux / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_upward_sensible_heat_flux / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of surface_upwelling_shortwave_flux_in_air_assuming_clear_sky / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_incoming_shortwave_flux / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_longwave_flux / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_longwave_flux_assuming_clear_sky / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_shortwave_flux / (W m-2) (time: 13; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_shortwave_flux / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of toa_outgoing_shortwave_flux_assuming_clear_sky / (W m-2) (time: 12; latitude: 3840; longitude: 5120)>,
<iris 'Cube' of x_wind / (m s-1) (time: 13; latitude: 3841; longitude: 5120)>,
<iris 'Cube' of y_wind / (m s-1) (time: 13; latitude: 3841; longitude: 5120)>]

In [8]:
from collections import defaultdict

In [31]:
t2c = defaultdict(list)
for c in c1:
    try:
        time = c.coord('time').points
    except:
        print(c.name(), 'no time')
    t2c[str(time.tolist())].append((c.name(), c.shape))
t2c

defaultdict(list,
            {'[438744.0333333333, 438745.0, 438746.0, 438747.0, 438748.0, 438749.0, 438750.0, 438751.0, 438752.0, 438753.0, 438754.0, 438755.0, 438756.0]': [('m01s01i202',
               (13, 3840, 5120)),
              ('air_temperature', (13, 3840, 5120)),
              ('dew_point_temperature', (13, 3840, 5120)),
              ('specific_humidity', (13, 3840, 5120)),
              ('toa_outgoing_shortwave_flux', (13, 3840, 5120)),
              ('x_wind', (13, 3841, 5120)),
              ('y_wind', (13, 3841, 5120))],
             '[438745.0, 438746.0, 438747.0, 438748.0, 438749.0, 438750.0, 438751.0, 438752.0, 438753.0, 438754.0, 438755.0, 438756.0]': [('m01s09i223',
               (12, 3840, 5120)),
              ('sea_ice_area_fraction', (12, 3840, 5120)),
              ('surface_air_pressure', (12, 3840, 5120)),
              ('surface_upward_latent_heat_flux', (12, 3840, 5120)),
              ('surface_upward_sensible_heat_flux', (12, 3840, 5120)),
           

In [38]:
t2c = defaultdict(list)
for c in c2:
    try:
        time = c.coord('time').points
    except:
        print(c.name(), 'no time')
    t2c[str(time.tolist())].append((c.name(), c.shape))
t2c

defaultdict(list,
            {'[[438744.0333333333, 438745.0, 438746.0, 438747.0, 438748.0, 438749.0, 438750.0, 438751.0, 438752.0, 438753.0, 438754.0, 438755.0, 438756.0, 438757.0, 438758.0, 438759.0, 438760.0, 438761.0, 438762.0, 438763.0, 438764.0, 438765.0, 438766.0, 438767.0, 438768.0], [438768.0333333333, 438769.0, 438770.0, 438771.0, 438772.0, 438773.0, 438774.0, 438775.0, 438776.0, 438777.0, 438778.0, 438779.0, 438780.0, 438781.0, 438782.0, 438783.0, 438784.0, 438785.0, 438786.0, 438787.0, 438788.0, 438789.0, 438790.0, 438791.0, 438792.0], [438792.0333333333, 438793.0, 438794.0, 438795.0, 438796.0, 438797.0, 438798.0, 438799.0, 438800.0, 438801.0, 438802.0, 438803.0, 438804.0, 438805.0, 438806.0, 438807.0, 438808.0, 438809.0, 438810.0, 438811.0, 438812.0, 438813.0, 438814.0, 438815.0, 438816.0]]': [('m01s01i202',
               (25, 3, 3840, 5120)),
              ('air_temperature', (25, 3, 3840, 5120)),
              ('dew_point_temperature', (25, 3, 3840, 5120)),
           

In [44]:
unique_times = {str(t.tolist()): t.flatten() for t in [c.coord('time').points for c in c2]}

In [53]:
import numpy as np
for arr in list(unique_times.values()):
    print(np.unique(np.diff(arr)))

[0.03333333 0.96666667 1.        ]
[1.]
[24.]
[1.]
[0. 1.]


In [56]:
c2.extract_cube('surface_temperature').coord('time').points

array([[438744., 438745., 438746., 438747., 438748., 438749., 438750.,
        438751., 438752., 438753., 438754., 438755., 438756., 438757.,
        438758., 438759., 438760., 438761., 438762., 438763., 438764.,
        438765., 438766., 438767., 438768.],
       [438768., 438769., 438770., 438771., 438772., 438773., 438774.,
        438775., 438776., 438777., 438778., 438779., 438780., 438781.,
        438782., 438783., 438784., 438785., 438786., 438787., 438788.,
        438789., 438790., 438791., 438792.],
       [438792., 438793., 438794., 438795., 438796., 438797., 438798.,
        438799., 438800., 438801., 438802., 438803., 438804., 438805.,
        438806., 438807., 438808., 438809., 438810., 438811., 438812.,
        438813., 438814., 438815., 438816.]])

In [29]:
t2c

defaultdict(list,
            {'[[438744.0333333333, 438745.0, 438746.0, 438747.0, 438748.0, 438749.0, 438750.0, 438751.0, 438752.0, 438753.0, 438754.0, 438755.0, 438756.0, 438757.0, 438758.0, 438759.0, 438760.0, 438761.0, 438762.0, 438763.0, 438764.0, 438765.0, 438766.0, 438767.0, 438768.0], [438768.0333333333, 438769.0, 438770.0, 438771.0, 438772.0, 438773.0, 438774.0, 438775.0, 438776.0, 438777.0, 438778.0, 438779.0, 438780.0, 438781.0, 438782.0, 438783.0, 438784.0, 438785.0, 438786.0, 438787.0, 438788.0, 438789.0, 438790.0, 438791.0, 438792.0], [438792.0333333333, 438793.0, 438794.0, 438795.0, 438796.0, 438797.0, 438798.0, 438799.0, 438800.0, 438801.0, 438802.0, 438803.0, 438804.0, 438805.0, 438806.0, 438807.0, 438808.0, 438809.0, 438810.0, 438811.0, 438812.0, 438813.0, 438814.0, 438815.0, 438816.0]]': [('m01s01i202',
               (25, 3, 3840, 5120)),
              ('air_temperature', (25, 3, 3840, 5120)),
              ('dew_point_temperature', (25, 3, 3840, 5120)),
           

In [36]:
list(t2c.keys())[0]

'[[438744.0333333333, 438745.0, 438746.0, 438747.0, 438748.0, 438749.0, 438750.0, 438751.0, 438752.0, 438753.0, 438754.0, 438755.0, 438756.0, 438757.0, 438758.0, 438759.0, 438760.0, 438761.0, 438762.0, 438763.0, 438764.0, 438765.0, 438766.0, 438767.0, 438768.0], [438768.0333333333, 438769.0, 438770.0, 438771.0, 438772.0, 438773.0, 438774.0, 438775.0, 438776.0, 438777.0, 438778.0, 438779.0, 438780.0, 438781.0, 438782.0, 438783.0, 438784.0, 438785.0, 438786.0, 438787.0, 438788.0, 438789.0, 438790.0, 438791.0, 438792.0], [438792.0333333333, 438793.0, 438794.0, 438795.0, 438796.0, 438797.0, 438798.0, 438799.0, 438800.0, 438801.0, 438802.0, 438803.0, 438804.0, 438805.0, 438806.0, 438807.0, 438808.0, 438809.0, 438810.0, 438811.0, 438812.0, 438813.0, 438814.0, 438815.0, 438816.0]]'

In [15]:
c1[2].coord('time').points

array([438744.03333333, 438745.        , 438746.        , 438747.        ,
       438748.        , 438749.        , 438750.        , 438751.        ,
       438752.        , 438753.        , 438754.        , 438755.        ,
       438756.        ])

In [16]:
c2 = iris.load(d2p[pd.Timestamp('2020-01-20 12:00')][0])

In [18]:
c2[2].coord('time').points

array([438757., 438758., 438759., 438760., 438761., 438762., 438763.,
       438764., 438765., 438766., 438767., 438768.])

In [20]:
iris.load(d2p[pd.Timestamp('2020-01-20 12:00')][0]).extract_cube('air_temperature').coord('time').points

array([438757., 438758., 438759., 438760., 438761., 438762., 438763.,
       438764., 438765., 438766., 438767., 438768.])

In [29]:
times = []
for date in pd.date_range('2020-01-20 00:00', '2020-01-23 12:00', freq='12h'):
    times.extend(iris.load(d2p[pd.Timestamp(date)][0]).extract_cube('air_temperature').coord('time').points.tolist())

In [30]:
import numpy as np

In [31]:
np.where(np.diff(times) != 1)

(array([ 0, 24, 25, 49, 50, 74, 75]),)

In [32]:
times

[438744.0333333333,
 438745.0,
 438746.0,
 438747.0,
 438748.0,
 438749.0,
 438750.0,
 438751.0,
 438752.0,
 438753.0,
 438754.0,
 438755.0,
 438756.0,
 438757.0,
 438758.0,
 438759.0,
 438760.0,
 438761.0,
 438762.0,
 438763.0,
 438764.0,
 438765.0,
 438766.0,
 438767.0,
 438768.0,
 438768.0333333333,
 438769.0,
 438770.0,
 438771.0,
 438772.0,
 438773.0,
 438774.0,
 438775.0,
 438776.0,
 438777.0,
 438778.0,
 438779.0,
 438780.0,
 438781.0,
 438782.0,
 438783.0,
 438784.0,
 438785.0,
 438786.0,
 438787.0,
 438788.0,
 438789.0,
 438790.0,
 438791.0,
 438792.0,
 438792.0333333333,
 438793.0,
 438794.0,
 438795.0,
 438796.0,
 438797.0,
 438798.0,
 438799.0,
 438800.0,
 438801.0,
 438802.0,
 438803.0,
 438804.0,
 438805.0,
 438806.0,
 438807.0,
 438808.0,
 438809.0,
 438810.0,
 438811.0,
 438812.0,
 438813.0,
 438814.0,
 438815.0,
 438816.0,
 438816.0333333333,
 438817.0,
 438818.0,
 438819.0,
 438820.0,
 438821.0,
 438822.0,
 438823.0,
 438824.0,
 438825.0,
 438826.0,
 438827.0,
 438828